In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import datetime

### Daily Reliance Stock data for 6 months.

In [3]:
data = yf.download("RELIANCE.NS",period="6mo")

[*********************100%%**********************]  1 of 1 completed

In [4]:
data.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-02-14,2329.949951,2381.899902,2323.649902,2378.100098,2378.100098,6609564
2023-02-15,2376.000000,2437.199951,2373.000000,2431.949951,2431.949951,15461902
2023-02-16,2449.449951,2463.800049,2425.050049,2430.050049,2430.050049,7967558
2023-02-17,2420.000000,2447.500000,2410.600098,2440.199951,2440.199951,5450092
2023-02-20,2445.000000,2449.750000,2410.100098,2414.399902,2414.399902,4078245

### Data for a specified range.

In [5]:
data = yf.download('RELIANCE.NS',start='2019-08-01',end='2020-05-01')

[*********************100%%**********************]  1 of 1 completed

In [6]:
data.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-08-01,1152.475708,1177.042847,1139.548218,1169.167480,1151.198608,10442920
2019-08-02,1164.660156,1186.998413,1151.187866,1173.229004,1161.594971,10968377
2019-08-05,1156.041870,1156.041870,1117.408081,1132.613892,1121.382690,14029195
2019-08-06,1124.094727,1138.805298,1111.464478,1117.705322,1106.621826,13414874
2019-08-07,1115.922119,1127.859009,1092.741943,1098.982788,1088.084961,11698729

### Intraday data

In [7]:
data = yf.download('RELIANCE.NS',period='1mo',interval='5m')

[*********************100%%**********************]  1 of 1 completed

In [8]:
data.head()

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-07-17 09:15:00+05:30,2748.550049,2749.949951,2736.949951,2736.949951,2736.949951,0
2023-07-17 09:20:00+05:30,2736.899902,2737.800049,2730.000000,2735.000000,2735.000000,219431
2023-07-17 09:25:00+05:30,2735.000000,2741.000000,2733.000000,2738.199951,2738.199951,176751
2023-07-17 09:30:00+05:30,2738.350098,2740.500000,2734.149902,2734.949951,2734.949951,79814
2023-07-17 09:35:00+05:30,2734.949951,2736.699951,2734.250000,2736.699951,2736.699951,80077

### Getting data for multiple tickers

In [46]:
tickers = ["ELECON.BO", "MAXIND.NS", "HLEGLAS.BO", "CHENNPETRO.NS", "POONAWALLA.NS", "INOXWIND.NS ", "WELENT.NS", "GIPL", "STARCEMENT.NS", "DATAMATICS.NS", "TALBROAUTO.NS", "THANGAMAYL.NS ", "NRBBEARING.NS", "GOKEX.NS", "FORTIS.NS", "SUNFLAG.NS", "LUMAXIND.NS", "BHARATWIRE.NS", "RAYMOND.NS", "MAZDOCK.NS", "ZENTEC.NS", "LUMAXIND.NS", "DYNAMATECH.NS", "JINDRILL.NS", "POLYMED.NS", "USHAMART.NS", "CIEINDIA.BO", "SOMANYCERA.NS", "LUMAXIND.NS", "HSCL.NS", "HTGC", "RIIL.NS", "VIPIND.NS ", "SCHNEIDER.NS", "HITECHGEAR.NS", "KTKBANK.NS", "RKFORGE.NS",  "UTTAMSUGAR.NS", "HINDWAREAP.NS", "SOMANYCERA.NS", "TALBROAUTO.NS", "KEC.NS", "WINDMACHIN.NS", "ACE.NS", "SPANDANA.NS", "POONAWALLA.NS", "ROSSELLIND.NS", "WABAG.NS", "MAHSEAMLES.NS", "SANGHVIMOV.NS", "TATACOFFEE.NS", "GPIL.NS", "MARKSANS.NS", "HBLPOWER.NS"]
start_date = datetime.datetime.today() - datetime.timedelta(days=100)
end_date = datetime.datetime.today()

close_price = pd.DataFrame()
for ticker in tickers:
    close_price[ticker] = yf.download(ticker,start_date,end_date)['High']

close_price.to_csv('high_name_Final.csv')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [36]:
close_price.head(100)
print(type(close_price))

<class 'pandas.core.frame.DataFrame'>

### Get all attributes(OHLC) and not only Adjusted Close Price

In [43]:
close_price.to_csv('high_name_Final.csv')

In [12]:
ohlcv_data = {}

In [13]:
for ticker in tickers:
    ohlcv_data[ticker] = yf.download(ticker,start_date,end_date)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [14]:
ohlcv_data['HDFCBANK.NS']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-08-22,1484.800049,1488.349976,1467.699951,1470.349976,1453.679321,4117033
2022-08-23,1453.300049,1475.949951,1450.400024,1465.800049,1449.181030,7483442
2022-08-24,1461.900024,1475.500000,1459.199951,1472.849976,1456.151001,6727760
2022-08-25,1479.900024,1486.800049,1457.000000,1464.849976,1448.241699,5911520
2022-08-26,1472.050049,1481.800049,1461.199951,1465.099976,1448.488892,3853088
...,...,...,...,...,...,...
2023-08-08,1651.699951,1655.599976,1642.050049,1649.900024,1649.900024,21886914
2023-08-09,1653.000000,1654.500000,1631.099976,1650.500000,1650.500000,16680618
2023-08-10,1647.050049,1654.250000,1631.000000,1635.849976,1635.849976,25390559
2023-08-11,1638.400024,1638.400024,1616.199951,1618.800049,1618.800049,14112911
2023-08-14,1611.000000,1615.000000,1600.250000,1610.900024,1610.900024,15652205

In [15]:
type(ohlcv_data)

dict